name: Fetch List Data

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행을 위한 설정

jobs:
  fetch-list-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests chardet selenium beautifulsoup4 webdriver-manager

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: List files in hrdnet_data directory before script
        run: ls -la ./hrdnet_data

      - name: Run list data script
        run: python3 ./hrdnet_data/detail.py

      - name: List files in hrdnet_data directory after script
        run: ls -la ./hrdnet_data

      - name: Commit and push changes if JSON files exist
        run: |
          git config --global user.email "kingsongsm97@gmail.com"
          git config --global user.name "Kingsong97"
          if ls ./hrdnet_data/*.json 1> /dev/null 2>&1; then
            git add ./hrdnet_data/*.json
            git commit -m "Update list data"
            git push
          else
            echo "No JSON files to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
